#!/bin/bash

rm -r "training set"
rm -r "testing set"
mkdir "training set"
cd "training set"
mkdir pos
mkdir neg
cd ..
mkdir "testing set"
cd "testing set"
mkdir pos
mkdir neg
cd ..

find pos | for i in {0..1000}
do
	read -r file
	if [ "$i" -lt "701" ];then
		cp "${file}" "training set/pos/"	
	else
		cp "${file}" "testing set/pos/"
	fi
done

find neg | for i in {0..1000}
do
	read -r file
        if [ "$i" -lt "701" ];then
                cp "${file}" "training set/neg/"
        else
                cp "${file}" "testing set/neg/"
        fi
done 
